version: '3.9'
services:

  frontend:
    build: ./Frontend
    restart: always
    ports:
      - "8080:5000"
    depends_on:
      - backend

  backend:
    build: ./Backend
    restart: always

  toolbox-curl:
    image: alpine/curl:8.10.0
    restart: always
    command: sleep infinity

  postgres:
    image: postgres:17
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./dev-init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 1qaz!QAZ
      POSTGRES_DB: bukep-epr

  toolbox-pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres