services:

  frontend:
    image: hexqueller/bukep-epr-frontend:latest
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - backend

  backend:
    image: hexqueller/bukep-epr-backend:latest
    restart: always
    # depends_on:
    # - Postgres 

  # postgres:
  #   image: postgres:17
  #   restart: always
