version: '3.9'
services:

  frontend:
    build: ./Frontend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - backend

  backend:
    build: ./Backend
    restart: always
    # depends_on:
    # - Postgres 

  # postgres:
  #   image: postgres:17
  #   restart: always
